version: 2
jobs:
  build:
    working_directory: ~/repo
    docker:
      - image: circleci/node:10.8.0
    parallelism: 4

    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run:
          name: Install a package, and any packages that it depends on
          command: npm i

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run:
          name: Build application with webpack
          command: npm run build
      - run: npm test

  deploy:
    docker:
      - image: circleci/node:10.8.0
    working_directory: ~/repo

    steps:
      - add_ssh_keys:
          fingerprints:
            - "c3:e7:f3:53:69:3a:11:2e:a1:f6:db:15:d9:16:af:47"

      - run: echo $REMOTE_HOSTKEY >> ~/.ssh/known_hosts
      - run:
          name: deploy
          command: |
            chmod -x deploy.sh
            . ./deploy.sh

            # rsync -avce ssh ~/repo $APP_USER@$TLD:/path/to/your/website


workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master
