version: 2
jobs:
  build:
    working_directory: ~/repo
    docker:
      - image: circleci/node:10.8.0
    parallelism: 4
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - "c3:e7:f3:53:69:3a:11:2e:a1:f6:db:15:d9:16:af:47"
      - run:
          name: Add public key
          command: |
            echo $REMOTE_HOSTKEY >> ~/.ssh/known_hosts
      - run:
          name: Install rsync
          command: |
            sudo apt-get update -y
            sudo apt-get -y install rsync
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-
      - run:
          name: Install packages
          command: npm ci
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run:
          name: Build application
          command: npm run build
      - run:
          name: Build service worker
          command: |
            npm run workbox
      # - run:
      #     name: Run tests
      #     command: |
      #       npm test
      - run:
          name: rsync
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              rsync -e ssh -arvc --exclude .git \
              --exclude .circleci \
              --exclude helpers \
              --exclude assets \
              --exclude components \
              --exclude layouts \
              --exclude pages \
              --exclude plugins \
              --exclude store \
              --exclude test \
              --exclude .editorconfig \
              --exclude .gitignore \
              --exclude package-lock.json \
              --exclude README.md \
              --exclude workbox-config.js \
              ~/repo/ \
              $APP_USER@$TLD:$APP_PATH && \
              ssh $APP_USER@$TLD "cd $APP_PATH; pm2 restart pwa"
            else
              echo "Not branch master."
            fi
