version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10
    parallelism: 4

    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: npm i

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run: npm run build

      # run tests!
      - run: npm test

  deploy:
    machine:
      enabled: true
    steps:
      - checkout
      - run:
          name: Deploy
          command: |
            ssh $USER@$TLD \
            'cd $PATH; git pull'
            echo "Wohoo!"

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master
