version: 2
jobs:
  build:
    working_directory: ~/repo
    parallelism: 4
    machine: true
    steps:
    - checkout
    - run:
        name: Build
        command: |
          TAG=0.1.$CIRCLE_BUILD_NUM
          docker build \
          --build-arg CMS_DOMAIN=$CMS_DOMAIN \
          --build-arg APP_DOMAIN=$APP_DOMAIN \
          --build-arg APP_NAME=$APP_NAME \
          -t $CONTAINER_NAME:$TAG .
    - run:
        name: Start Container
        command: |
          docker run -d --name $CONTAINER_NAME $CONTAINER_NAME:$TAG
