version: 2
jobs:
  build:
    working_directory: ~/repo
    docker:
      - image: circleci/node:10.8.0
    parallelism: 4

    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: npm i

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run: npm run build
      - run: npm test

  deploy:
    working_directory: ~/repo
    docker:
      - image: circleci/node:10.8.0
    steps:
      - add_ssh_keys:
          fingerprints:
            - "c3:e7:f3:53:69:3a:11:2e:a1:f6:db:15:d9:16:af:47" # dlbr
      - checkout
      - run:
          name: Deploy
          command: |
            ssh $APP_USER@$APP_DOMAIN 'cd $APP_PATH; git pull'

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master
